services:
  persistence: 
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: persistence
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      smo:
        ipv4_address: 172.40.0.30
        ipv6_address: 2001:db8:1:1::30

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "persistence"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      smo:
        ipv4_address: 172.40.0.31
        ipv6_address: 2001:db8:1:1::31

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: kibana
    links:
      - "persistence"
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://persistence:9200
    networks:
      smo:
        ipv4_address: 172.40.0.32
        ipv6_address: 2001:db8:1:1::32

  odlux:
    image: nexus3.onap.org:10001/onap/sdnc-web-image:2.6.1
    container_name: odlux
    hostname: odlux
    ports:
      - "8080:8080"
    environment:
      ENABLE_OAUTH: false
      WEBPROTOCOL: HTTP
      WEBPORT: 8080
      SDNRPROTOCOL: http
      SDNRHOST: controller
      SDNRPORT: 8181
    depends_on:
      controller:
        condition: service_healthy
    networks:
      smo:
        ipv4_address: 172.40.0.33
        ipv6_address: 2001:db8:1:1::33

  controller:
    image: nexus3.onap.org:10001/onap/sdnc-image:2.6.1
    container_name: controller
    hostname: controller
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8181/ready || exit 1
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8181:8181"
      - "8101:8101"
    environment:
      ENABLE_ODL_CLUSTER: false
      ENABLE_OAUTH: false
      ODL_CERT_DIR: /opt/opendaylight/current/certs
      ODL_ADMIN_PASSWORD: admin
      SDNC_CONFIG_DIR: /opt/onap/ccsdk/data/properties
      SDNC_REPLICAS: 0
      CCSDK_REPLICAS: 0
      DOMAIN: ""
      SDNRWT: true
      SDNRONLY: true
      SDNRINIT: true
      SDNRDBURL: http://persistence:9200
      SDNR_NETCONF_CALLHOME_ENABLED: true
      A1_ADAPTER_NORTHBOUND: false
      JAVA_OPTS: -Xms256m -Xmx4g
      SDNR_VES_COLLECTOR_ENABLED: false
    volumes:
      - ./controller/certs/certs.properties:/opt/opendaylight/current/certs/certs.properties
      - ./controller/certs/keys0.zip:/opt/opendaylight/current/certs/keys0.zip
    networks:
      smo:
        ipv4_address: 172.40.0.34
        ipv6_address: 2001:db8:1:1::34

networks:
  smo:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.40.0.0/16
        gateway: 172.40.0.1
      - subnet: 2001:db8:1:1::/64
        gateway: 2001:db8:1:1::1
