services:
  persistence: 
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: persistence
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      smo:

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "persistence"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      smo:

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: kibana
    links:
      - "persistence"
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://persistence:9200
    networks:
      smo:

networks:
  smo:
    external: true
