services:
  odlux:
    image: nexus3.onap.org:10001/onap/sdnc-web-image:2.6.1
    container_name: odlux
    hostname: odlux
    ports:
      - "8080:8080"
    environment:
      ENABLE_OAUTH: false
      WEBPROTOCOL: HTTP
      WEBPORT: 8080
      SDNRPROTOCOL: http
      SDNRHOST: controller
      SDNRPORT: 8181
    depends_on:
      controller:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: sdnc
    networks:
      smo:

  controller:
    image: nexus3.onap.org:10001/onap/sdnc-image:2.6.1
    container_name: controller
    hostname: controller
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8181/ready || exit 1
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8181:8181"
      - "8101:8101"
    environment:
      ENABLE_ODL_CLUSTER: false
      ENABLE_OAUTH: false
      ODL_CERT_DIR: /opt/opendaylight/current/certs
      ODL_ADMIN_PASSWORD: admin
      SDNC_CONFIG_DIR: /opt/onap/ccsdk/data/properties
      SDNC_REPLICAS: 0
      CCSDK_REPLICAS: 0
      DOMAIN: ""
      SDNRWT: true
      SDNRONLY: true
      SDNRINIT: true
      SDNRDBURL: http://persistence:9200
      SDNR_NETCONF_CALLHOME_ENABLED: true
      A1_ADAPTER_NORTHBOUND: false
      JAVA_OPTS: -Xms256m -Xmx4g
      SDNR_VES_COLLECTOR_ENABLED: false
    volumes:
      - ./controller/certs/certs.properties:/opt/opendaylight/current/certs/certs.properties
      - ./controller/certs/keys0.zip:/opt/opendaylight/current/certs/keys0.zip
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: sdnc
    networks:
      smo:

networks:
  smo:
    external: true
